### ISSUE TITLE
Import declaration conflicts with local declaration of 'Action'.

### ISSUE THREAD

**Issue by ashishkujoy** [ionic-team/stencil-redux#72] opened 2019-12-11 15:36 UTC
Hi Getting this compilation error with stencil-redux 0.1.1 and 0.1.0

```bash

TypeScript: node_modules/@stencil/redux/dist/types/global/interfaces.d.ts:1:10
           Import declaration conflicts with local declaration of 'Action'.

      L1:  import { Action, AnyAction, Store as ReduxStore, Unsubscribe } from 'redux';
      L2:  export interface Store<S = any, A extends Action = AnyAction> {

```

on removing 
```javascript
export declare type Action = (...args: any[]) => any;
```
from node_modules/@stencil/redux/dist/types/global/interfaces.d.ts
It got compiled.

Here is my .tsconfig.json
```json
{
  "compilerOptions": {
    "allowSyntheticDefaultImports": true,
    "allowUnreachableCode": false,
    "declaration": false,
    "experimentalDecorators": true,
    "lib": [
      "dom",
      "es2017"
    ],
    "moduleResolution": "node",
    "module": "esnext",
    "target": "es2016",
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "jsx": "react",
    "jsxFactory": "h"
  },
  "include": [
    "src",
    "types/jsx.d.ts"
  ],
  "exclude": [
    "node_modules"
  ]
}

```

Could you please help us with this. And please let me know if any other information is required.

**Comment by dwieeb** [comment] 2019-12-11 19:37
Duplicate of https://github.com/ionic-team/stencil-redux/issues/69

**Comment by dwieeb** [comment] 2019-12-11 19:38
Here is the issue we're using to discuss options: https://github.com/ionic-team/stencil-redux/issues/71

**Closed** 2019-12-11 19:37 UTC
